services:
  scell-jpro:
    image: scalablecomponents/scell-web-jpro:temurin-jre21-0.0.1
    ports:
      - 18080-18120:8080-8120
    volumes:
      - ./logs:/opt/jpro-loadbalancer/logs
      - ./files/jpro-loadbalancer-0.13.0.jar:/opt/jpro-loadbalancer/jpro-loadbalancer.jar
      - ./files/SCell-1.3.40-java11_web-3.0.13_2024.3.1-CLIPBOARDFIX-jpro.zip:/opt/jpro-loadbalancer/scellweb.zip
      - ./files/application.properties:/opt/jpro-loadbalancer/application.properties
      - ./files/xlsxs:/opt/jpro-loadbalancer/xlsxs
    environment:
      SCELL_WEB_FONTS_FOLDER_1: /usr/share/fonts/truetype/msttcorefonts/
      SCELL_WEB_SHOW_WATERMARK: False
      SCELL_WEB_DEMO_FILE_FULL_PATH_1: /opt/jpro-loadbalancer/xlsxs/demo.xlsx
