services:
  scell-jpro:
    image: scalablecomponents/scell-web-jpro:temurin-jre21-0.0.2
    ports:
      - 18081-18120:18080-18120
    volumes:
      - ./files/jpro-logs:/opt/jpro-loadbalancer/logs
      - ./files/ssl:/opt/jpro-loadbalancer/ssl
      - ./files/apache-logs:/opt/apache-logs
      - ./files/jpro-loadbalancer-0.15.0-SNAPSHOT.jar:/opt/jpro-loadbalancer/jpro-loadbalancer.jar
      - ./files/SCell-1.6.1-java11_web-3.5.0_2025.1.0-jpro.zip:/opt/jpro-loadbalancer/scellweb.zip
      - ./files/application.properties:/opt/jpro-loadbalancer/application.properties
      - ./files/xlsxs:/opt/jpro-loadbalancer/xlsxs
    environment:
      SCELL_WEB_FONTS_FOLDER_1: /usr/share/fonts/truetype/msttcorefonts/
      SCELL_WEB_SHOW_WATERMARK: False
      SCELL_WEB_DEMO_FILE_FULL_PATH_1: /opt/jpro-loadbalancer/xlsxs/demo.xlsx
      JPRO_SERVER_PORT: 18080
      JPRO_LOADBALANCER_START_PORT: 18100
      RUN_APACHE_HTTPS: True
      APACHE_HTTPS_HOST: intechcore.space
      APACHE_HTTPS_PORT: 18120
      APACHE_HTTPS_COMMON_CONFIG: options-ssl-apache.conf
      APACHE_SSL_CERTIFICATE_FILE: fullchain11.pem
      APACHE_SSL_CERTIFICATE_KEY_FILE: privkey11.pem


